/*******************************************************************************
 * VMotor generated by Eliot.UELib using UELib.CLI.
 * Eliot.UELib © 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class VMotor extends VAxle
	native
	exportstructs;

enum EMotorConstant
{
	MOTORC_Drive0,
	MOTORC_Drive1,
	MOTORC_Drive2,
	MOTORC_Brake0,
	MOTORC_Brake1,
	MOTORC_Brake2
};

var() SVehiclePhysicsMotorProperties MotorProps;
var float Input;
var const transient float DriveMagnitude;
var const transient float BrakeMagnitude;
var const transient float RPMs;
var const transient float BestRPMs;
var const transient float MaxRPMs;

defaultproperties
{
	bCaresAboutAcceleration=true
}