/*******************************************************************************
 * UDukeListSliderArrowButton generated by Eliot.UELib using UELib.CLI.
 * Eliot.UELib © 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class UDukeListSliderArrowButton extends UWindowButton;

var bool bLeft;
var Color DrawColor;

function BeforePaint(Canvas C, float X, float Y)
{
	super(UWindowDialogControl).BeforePaint(C, X, Y);
	// End:0x45
	if(bLeft)
	{
		OverRegion.X = 203;
		DownRegion.X = 203;
		UpRegion.X = 203;
	}
	return;
}

function Paint(Canvas C, float X, float Y)
{
	C.DrawColor = DrawColor;
	super.Paint(C, X, Y);
	return;
}

function bool CheckMousePassThrough(float X, float Y)
{
	// End:0x4C
	if(__NFUN_148__(__NFUN_148__(__NFUN_340__(ParentWindow, none), __NFUN_340__(ParentWindow.ParentWindow, none)), __NFUN_340__(ParentWindow.ParentWindow.ChildInFocus, ParentWindow)))
	{
		return true;
	}
	return false;
	return;
}

defaultproperties
{
	DrawColor=(B=36,G=1,R=255,A=37)
	bStretched=true
	bSolid=true
	UpTexture='Menu.Menu.Backdrop'
	DownTexture='Menu.Menu.Backdrop'
	OverTexture='Menu.Menu.Backdrop'
	UpRegion=(X=233,Y=74,W=27,h=34)
	DownRegion=(X=233,Y=74,W=27,h=34)
	OverRegion=(X=233,Y=74,W=27,h=34)
	bUseRegion=true
	bNoKeyboard=true
}