/*******************************************************************************
 * acGeneric_Combat generated by Eliot.UELib using UELib.CLI.
 * Eliot.UELib © 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class acGeneric_Combat extends acGeneric_Shared;

defaultproperties
{
	bUseSimplePain=true
	Animations=none
}