/*******************************************************************************
 * AssaultTrooper_Weapon generated by Eliot.UELib using UELib.CLI.
 * Eliot.UELib © 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class AssaultTrooper_Weapon extends FakeAIWeapon
	collapsecategories;

defaultproperties
{
	MuzzleBones(0)=StateTableIndex
	MuzzleBones(1)=Ident
}