/*******************************************************************************
 * BattleLord_Armor_LeftArm generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class BattleLord_Armor_LeftArm extends BattleLord_Armor;

defaultproperties
{
    DestroyedPrePivot=(X=-5,Y=-25,Z=-15)
    StaticMesh='sm_armor.BattleLord_Armor.battlelord_armor4'
}