/*******************************************************************************
 * Cycloid_PowerConduit generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class Cycloid_PowerConduit extends aFinalDecoration
    collapsecategories;

defaultproperties
{
    HealthPrefab=0
}