/*******************************************************************************
 * Cycloid_AttackBeam generated by Eliot.UELib using UELib.CLI.
 * Eliot.UELib © 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class Cycloid_AttackBeam extends BeamSystem
	collapsecategories
	hidecategories(Filter,HeatVision,Interactivity,Karma,KarmaObject,KarmaOverride,Lighting,Networking,ParticleSystemBase,ParticleTextureInfo,SoftParticleSystem,Sound,SpawnOnDestroyed);

var float DamagePlayer;
var float DamageNonPlayer;
var SoftParticleSystem HitParticleSystem;
var class<SoftParticleSystem> HitParticleSystemClass;

simulated function PostVerifySelf()
{
	local Actor A;

	// End:0x14
	if(__NFUN_169__(string(BeamSegments), 1))
	{
		string(BeamSegments) = 1;
	}
	BeamSegments[0].Actor1 = self;
	super(RenderActor).PostVerifySelf();
	__NFUN_361__('Tick');
	return;
}

final function ActivateBeam()
{
	Enabled = true;
	TickStyle = default.TickStyle;
	return;
}

final function DeactivateBeam()
{
	Enabled = false;
	TickStyle = 0;
	return;
}

event Touch(Actor Other)
{
	local float dmg;

	super(Actor).Touch(Other);
	// End:0x2C
	if(Other.bIsPlayerPawn)
	{
		dmg = DamagePlayer;		
	}
	else
	{
		dmg = DamageNonPlayer;
	}
	Other.TakeDamage(none, dmg, Other.Location, __NFUN_232__(0, 0, 1), class'ExplosionDamage');
	return;
}

defaultproperties
{
	Enabled=false
	BeamStartWidth=10
	BeamEndWidth=10
	DynamicBeamPoints=100024
	BeamTexture='dt_Effects2.Beams.BlueBeam03_FBM'
	BeamTextureScaleX=0.25
	BeamTexturePanX=32
	BeamTextureRotate=90
	BeamSegments=/* Array type was not detected. */
	Cond=/* Unknown default property type! */
	GotoNearTarget=/* Unknown default property type! */
	acBugball_WallSocket=/* Unknown default property type! */
}