/*******************************************************************************
 * dnExplosionLight_CycloidMortar generated by Eliot.UELib using UELib.CLI.
 * Eliot.UELib © 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class dnExplosionLight_CycloidMortar extends dnExplosionLight
	hidecategories(Collision,Filter,HeatVision,Interactivity,Karma,KarmaObject,KarmaOverride,Networking,SpawnOnDestroyed);

defaultproperties
{
	FadeOutTime=1
	LightRadius=2048
	LightIntensity=8
	LightColor=(B=87,G=5,R=1,A=236)
	TickStyle=3
}