/*******************************************************************************
 * EnforcerCorpse generated by Eliot.UELib using UELib.CLI.
 * Eliot.UELib © 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class EnforcerCorpse extends AlienCorpse;

defaultproperties
{
	FadeDelay=4
	TimeToFade=1
	bActorColorFade=true
	ActorColorToFade=Generic0
}