/*******************************************************************************
 * PopUpCfg_CrouchFire generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class PopUpCfg_CrouchFire extends PopUpCfg
    exportstructs
    hidecategories(Object);

defaultproperties
{
    AnimCtrler=2
    AnimExtension="Fire"
    SingleAnim=true
    RequiresTarget=false
    AllowFireOnOut=true
    AllowFireOnHold=false
    IntervalMin=0
    ExposureMin=-1
    ExposureRnd=-1
}