/*******************************************************************************
 * RatCorpse generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class RatCorpse extends AICorpse;

defaultproperties
{
    CollisionRadius=10
    CollisionHeight=3.5
    Mass=10
    DrawScale=0.7
}