/*******************************************************************************
 * ScriptMethod_DigsGirl_FinishFlirt_NativeBase generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class ScriptMethod_DigsGirl_FinishFlirt_NativeBase extends ScriptMethod
    native
    exportstructs
    hidecategories(Object);

cpptext
{
// Stripped
}

event FinishFlirt(AIActor MyGirl)
{
    return;
}
