/*******************************************************************************
 * ScriptMethod_StandCombat generated by Eliot.UELib using UELib.CLI.
 * Eliot.UELib © 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class ScriptMethod_StandCombat extends ScriptMethod
	native
	exportstructs
	hidecategories(Object);

cpptext
{
// Stripped
}

event string GetMethodString()
{
	return "StandCombat ()";
	return;
}

defaultproperties
{
	Latent=true
}