struct SGotoX
{
	var Engine.BaseAI.EAITargetType TargetType;
	var Actor TargetActor;
	var Vector TargetPos;
	var Actor RefActor;
	var Vector NextPos;
	var int FinalDest;
	var Engine.BaseAI.EAIOffsetType OffsetType;
	var float Range;
	var float Bearing;
	var float Height;
	var float ClipTolerance;
	var Engine.BaseAI.EAIMoveSpeed Speed;
	var float SpeedScale;
	var Engine.BaseAI.EAIFocus Focus;
	var Actor FocusActor;
	var Vector FacePos;
	var int RefId;
	var Engine.BaseAI.EAIGotoXMode Mode;
	var float SideArcTurnSpeedThresh;
	var float StepBackwardsSpeedThresh;
	var float StartAngleSideSector;
	var float StartAngleBackSector;
	var float MoveBackwardsDistThresh;
	var float SideStepDistThresh;
	var int MaxSteps;
	var bool PreVerified;
	var int TurnDir;
	var DoorMoverEx MyDoorEx;
	var bool ForceEval;
	var bool ForceAnim;
	var transient float AnimChangeGate;
	var float StuckTime;
	var transient float Gate;
	var bool bStopToTurn;
	var transient float EvalGate;
	var transient float EvalGateTime;
	var int EvalCount;
	var bool bDisableEvalGate;
	var float ConstraintStrengthOverride;
	var Engine.BaseAI.EAIPathFailMode PathFailMode;
	var bool bWaitingOnDynamicBlocker;
	var float bWaitTime;
	var Vector TargetExtent;
	var bool bDebug;
	var float FlyConstraintStrength;
	var bool bUseAccelerationWhenFlying;
	var bool ExitOnLand;
	var float ExitOnLandHeight;
	var Engine.Object.EBitModifier UseAnimDispDirMod;
};