/*******************************************************************************
 * CharacterVoicePack generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class CharacterVoicePack extends Object
    abstract
    native;

cpptext
{
// Stripped
}

var() array<SCharacterSoundInfo> CharacterSounds;
var() SSoundInfo NoSound;

final simulated function FindSoundEx(name GroupName, out SSoundInfo out_SoundInfo)
{
    local int i;

    i = 0;
    J0x07:

    // End:0x54 [Loop If]
    if(-i)
    {        
        // End:0x4A
        if(__NFUN_341__(CharacterSounds[i].GroupName, GroupName))
        {
            out_SoundInfo = CharacterSounds[i].SoundInfo;
            return;
        }
        // [Loop Continue]
        i += ;
    }
    out_SoundInfo = NoSound;
    return;
}
