/*******************************************************************************
 * Triggers generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class Triggers extends InfoActor
    native
    collapsecategories
    notplaceable
    hidecategories(Filter,Interactivity,Karma,Lighting,Networking,Sound);

enum EKillTriggerType
{
    KT_Enable,
    KT_Disable,
    KT_Toggle,
    KT_Random,
    KT_Reset
};

defaultproperties
{
    bHidden=true
    CollisionRadius=40
    CollisionHeight=40
    TraceFireHitResponse=1
    RemoteRole=0
}