/*******************************************************************************
 * dnBonePartMapper_AssaultTrooper_RightLeg generated by Eliot.UELib using UELib.CLI.
 * Eliot.UELib © 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class dnBonePartMapper_AssaultTrooper_RightLeg extends BonePartMapper
	exportstructs;

defaultproperties
{
	PartMapping=/* Array type was not detected. */
	EndingBlendAlpha=/* Unknown default property type! */
	DestroyableBones=/* Array type was not detected. */
	StartingBlendAlpha=false
	bSurviveDismount=false
	bDontScaleByDrawScale=false
	bScaleByDrawScaleNonDefault=false
	bTransformDrawScale3DChange=false
	bTakeParentTag=false
	bTransferToCorpse=false
	bDontSetOwner=false
	MountParentTag=None
	DrawScaleOverride=0
	AppendToTag=None
	ForceTag=None
	ForceEvent=None
	MountMeshItem=None
	MountOrigin=(X=1.292418E-41,Y=2.94903E-17,Z=0)
	MountOriginVariance=(X=1.292418E-41,Y=2.94903E-17,Z=0)
	MountAngles=(Pitch=8741,Yaw=572915712,Roll=0)
	MountAnglesVariance=(Pitch=8741,Yaw=572915712,Roll=0)
	MountType=0
	DismountPhysics=0
}