/*******************************************************************************
 * dnBreakableGlass_Mirror generated by Eliot.UELib using UELib.CLI.
 * Eliot.UELib © 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class dnBreakableGlass_Mirror extends dnBreakableGlass
	collapsecategories;

defaultproperties
{
	bClearMirrorRenderTargetOnShatter=true
	bOneSidedMirror=true
	Skins(0)='dt_masking.GlassMirror_Materials.GlassMirrorDirty1_FinalBlend'
	Skins(1)='dt_masking.GlassMirror_Materials.BrokenGlassMirror_1024_FinalBlend'
	Skins(2)='dt_masking.GlassMirror_Materials.BrokenGlassMirror_1024_FinalBlend'
	Skins(3)='dt_masking.Glass_Materials.glassdirty1bc_finalblend'
	MirrorRenderTarget='dt_masking.GlassMirror_Materials.glassmirror_rendertarget1024'
}