/*******************************************************************************
 * dnFlybyPlane_Fighter_VaporBeam generated by Eliot.UELib using UELib.CLI.
 * Eliot.UELib © 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class dnFlybyPlane_Fighter_VaporBeam extends BeamTrail
	collapsecategories
	hidecategories(Filter,HeatVision,Interactivity,Karma,KarmaObject,KarmaOverride,Lighting,Networking,ParticleSystemBase,ParticleTextureInfo,SoftParticleSystem,Sound,SpawnOnDestroyed);

defaultproperties
{
	BeamStartWidth=30
	BeamEndWidth=30
	AlphaAnimStart=0.5
	AlphaMidPercent=0.25
	BeamTexture='dt_Effects2.Smoke.SkokeLine_BeamTrail'
	BeamTextureRotate=90
	ActorColorList(0)=(ActorColor=(B=121,G=2,R=1,A=255),G=255,B=255,A=255)
}