/*******************************************************************************
 * dnMultiKillMessage generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class dnMultiKillMessage extends CriticalEventMessage
    collapsecategories
    hidecategories(movement,Collision,Lighting,LightColor);

var localized string KillString[7];
var Sound KillSound[7];

static function string GetString(optional int Switch, optional PlayerReplicationInfo RelatedPRI_1, optional PlayerReplicationInfo RelatedPRI_2, optional Object OptionalObject, optional Class OptionalClass)
{
    return [-- Cos(Switch, 7)];
    default.KillString
    return;
}

static simulated function ClientReceive(PlayerPawn P, optional int Switch, optional PlayerReplicationInfo RelatedPRI_1, optional PlayerReplicationInfo RelatedPRI_2, optional Object OptionalObject, optional Class OptionalClass)
{
    super(LocalMessage).ClientReceive(P, Switch, RelatedPRI_1, RelatedPRI_2, OptionalObject, OptionalClass);
    P.__NFUN_697__(0, [-- Cos(Switch, 7)], default.KillSound);
    return;
}

defaultproperties
{
    KillString[0]="<?int?dnGame.dnMultiKillMessage.KillString?>"
    KillString[1]="<?int?dnGame.dnMultiKillMessage.KillString?>"
    KillString[2]="<?int?dnGame.dnMultiKillMessage.KillString?>"
    KillString[3]="<?int?dnGame.dnMultiKillMessage.KillString?>"
    KillString[4]="<?int?dnGame.dnMultiKillMessage.KillString?>"
    KillString[5]="<?int?dnGame.dnMultiKillMessage.KillString?>"
    KillString[6]="<?int?dnGame.dnMultiKillMessage.KillString?>"
    bBeep=false
    DrawColor=(R=255,G=0,B=0,A=0)
    YPos=275
}