/*******************************************************************************
 * InventoryDrain_ZoomMode generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class InventoryDrain_ZoomMode extends InventoryDrain_Energy;

defaultproperties
{
    DrainTime=0
}