/*******************************************************************************
 * ParticleSystemTimer_Sparks_Malfunction_Gunship generated by Eliot.UELib using UELib.CLI.
 * Eliot.UELib © 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class ParticleSystemTimer_Sparks_Malfunction_Gunship extends ParticleSystemTimer_Sparks_Malfunction
	collapsecategories
	hidecategories(Filter,Interactivity,Karma,Lighting,Networking,Actor,Collision,Display,HeatVision,Interpolation,Material,Tick,TickTules,ParticleSystemTimer_Display,ParticleSystemTimer_Sound);

defaultproperties
{
	ParticleSystemClass='p_Decorations.Electrical_Malfunction.Electrical_Malfunction_Sparks_Gunship_PST'
}