/*******************************************************************************
 * Barrels_Generic_Explosive01 generated by Eliot.UELib using UELib.CLI.
 * Eliot.UELib © 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class Barrels_Generic_Explosive01 extends Barrels_Generic_Explosive01_NoGibs
	collapsecategories;

defaultproperties
{
	bExplodeOnNextHit=false
	SpawnOnDestroyed=/* Array type was not detected. */
}