/*******************************************************************************
 * Barrels_Generic_Explosive01_Gib_C generated by Eliot.UELib using UELib.CLI.
 * Eliot.UELib © 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class Barrels_Generic_Explosive01_Gib_C extends Barrels_Generic_Explosive01_Gibs;

defaultproperties
{
	ForcedIndex=2
	CollisionRadius=5
	CollisionHeight=10
	StaticMesh='sm_class_decorations.Barrels.Barrel_Gib_Piece_2'
}