/*******************************************************************************
 * Cannister_Generic_Gibs_Shard_Small generated by Eliot.UELib using UELib.CLI.
 * Eliot.UELib © 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class Cannister_Generic_Gibs_Shard_Small extends Cannister_Generic_Gibs;

defaultproperties
{
	ForcedIndex=0
}