/*******************************************************************************
 * Containers_Crates_ItemCrate_Gib_Wood_Back generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class Containers_Crates_ItemCrate_Gib_Wood_Back extends Containers_Crates_ItemCrate_Gibs
    collapsecategories;

defaultproperties
{
    ForcedIndex=3
    StaticMesh='sm_class_decorations.Crate.AmmoCrate03_Gib'
}