/*******************************************************************************
 * DecoGlass_SodaFountain generated by Eliot.UELib using UELib.CLI.
 * Eliot.UELib © 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class DecoGlass_SodaFountain extends dnBreakableGlass_DecoGlass
	collapsecategories;

defaultproperties
{
	ParticleSize=3
	bRandomTextureRotation=false
	bAlignTextureOnBreak=false
	bStaticEdgePieces=false
	DrawScale3D=(X=1.291717E-41,Y=2.802819E-17,Z=15)
	Skins(0)='smt_skins8.SodaFountain.sodaftn_drnksign_bs'
	Skins(1)='smt_skins8.SodaFountain.sodaftn_drnksign_bs'
	Skins(2)='smt_skins8.SodaFountain.sodaftn_drnksign_bs'
	Skins(3)='smt_skins8.SodaFountain.sodaftn_drnksign_bs'
}