/*******************************************************************************
 * DecoGlass_Microwave generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class DecoGlass_Microwave extends dnBreakableGlass_DecoGlass
    collapsecategories
    dependson(Electronics_Generic_Microwave);

var Electronics_Generic_Microwave MicrowaveActor;

event GlassCracked()
{
    super(dnBreakableGlass).GlassCracked();
    DecoGlassDamaged();
    return;
}

event GlassShattered()
{
    super(dnBreakableGlass).GlassShattered();
    DecoGlassDamaged();
    return;
}

final function DecoGlassDamaged()
{
    // End:0x1C
    if(__NFUN_340__(MicrowaveActor, none))
    {
        MicrowaveActor.GlassDamaged();
    }
    MicrowaveActor = none;
    return;
}

final function CrackSelf()
{
    MicrowaveActor = none;
    __NFUN_1080__(Location);
    return;
}

defaultproperties
{
    ParticleSize=3
    bRandomTextureRotation=false
    bAlignTextureOnBreak=false
    bStaticEdgePieces=false
    bDrawHUDInfo=true
    bForceUsePhrase=true
    bUsable=true
    StaticInteractionClassification=3
    DynamicInteractionClassification=1
    PhysicsEntityGroup=MicrowaveEntityGroup
    DrawScale3D=(X=18,Y=16.5,Z=1)
    Skins(0)='mt_Skins.Microwave.microwaveglass_fblend'
    Skins(1)='mt_Skins.Microwave.microwaveglass_fblend'
    Skins(2)='mt_Skins.Microwave.microwaveglass_fblend'
    Skins(3)='mt_Skins.Microwave.microwaveglass_fblend'
}