/*******************************************************************************
 * Details_Books generated by Eliot.UELib using UELib.CLI.
 * Eliot.UELib © 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class Details_Books extends Details_Generic
	abstract
	collapsecategories;

defaultproperties
{
	bSurviveDeath=true
	DestroyedActivities(0)=none
	DestroyedActivities(1)='dnGame.DecoActivityDeclarations.DA_Sound_Destroyed_Wood_Small'
	SpawnOnDestroyedSimple(0)='dnParticles.dnDebris_Paper1'
	SpawnOnDestroyedSimple(1)='dnParticles.dnDebris_Smoke'
	bTickOnlyWhenPhysicsAwake=true
	PhysicsMaterial='dnMaterial.dnPhysicsMaterial_Cardboard'
	Physics=18
	CollisionRadius=12
	CollisionHeight=8
	Mass=15
	DrawType=2
}