/*******************************************************************************
 * Details_Generic_PhysicsHelperNode generated by Eliot.UELib using UE Explorer.exe.
 * Eliot.UELib ? 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class Details_Generic_PhysicsHelperNode extends Details_Generic
    collapsecategories;

defaultproperties
{
    HealthPrefab=0
    bModifyTickOnPhysicsChange=false
    bTickOnlyWhenPhysicsAwake=true
    DynamicInteractionClassification=8
    KLinearDamping=1
    KAngularDamping=1
    Physics=18
    bHidden=true
    bCanExistOutOfWorld=true
    bTickOnlyWhenOwnerShould=true
    bCollideActors=false
    bCollideWorld=false
    TickStyle=2
    StaticMesh='sm_geo_decorations.CollisionPrimitives.CP_Cube_64'
}