/*******************************************************************************
 * Details_Generic_CigarBox generated by Eliot.UELib using UELib.CLI.
 * Eliot.UELib © 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class Details_Generic_CigarBox extends Details_Generic
	collapsecategories;

defaultproperties
{
	HealthPrefab=0
	bTickOnlyWhenPhysicsAwake=true
	PhysicsMaterial='dnMaterial.dnPhysicsMaterial_Wood_Solid'
	Physics=18
	CollisionRadius=6
	CollisionHeight=2
	Mass=10
	DrawType=2
	Mesh='c_generic.CigarBox'
}