/*******************************************************************************
 * Plants_Generic_Cactus generated by Eliot.UELib using UELib.CLI.
 * Eliot.UELib © 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class Plants_Generic_Cactus extends Plants_Generic
	abstract
	collapsecategories;

simulated event Destroyed()
{
	local dnScreenSplatter_CactusJuice ScreenSplatter;

	ScreenSplatter = dnScreenSplatter_CactusJuice(FindStaticActor(class'dnScreenSplatter_CactusJuice'));
	// End:0x44
	if(__NFUN_340__(ScreenSplatter, none))
	{
		ScreenSplatter.__NFUN_645__(Location);
		ScreenSplatter.ExecuteEffect();
	}
	super(dnDecoration).Destroyed();
	return;
}

event RegisterPrecacheComponents(PrecacheIndex PrecacheIndex)
{
	super(dnDecoration).RegisterPrecacheComponents(PrecacheIndex);
	PrecacheIndex.__NFUN_1266__(class'dnScreenSplatter_CactusJuice');
	return;
}

defaultproperties
{
	bSurviveDeath=false
	DestroyedActivities(0)=none
	begin object name=DA_Sound_Cactus_Gibs class=DecoActivities_Sound
		SoundNames(0)=CactusGib
	object end
	// Reference: DecoActivities_Sound'Plants_Generic_Cactus.DA_Sound_Cactus_Gibs'
	DestroyedActivities(1)=DA_Sound_Cactus_Gibs
	HealthPrefab=2
	SpawnOnDestroyedSimple(0)='dnParticles.dnDebris_Smoke'
	bBlockCamera=false
	bAcceptsDecalProjectors=false
	bLowerByCollision=false
}