/*******************************************************************************
 * dnCharacterFX_Water_FootSplash generated by Eliot.UELib using UELib.CLI.
 * Eliot.UELib © 2009-2022 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class dnCharacterFX_Water_FootSplash extends dnCharacterFX
	collapsecategories
	hidecategories(Filter,HeatVision,Interactivity,KarmaObject,KarmaOverride,Networking);

defaultproperties
{
	DestroyWhenEmpty=true
	UseZoneGravity=false
	AdditionalSpawn=/* Array type was not detected. */
	bFireAndForget=/* Unknown default property type! */
}